# Generated by Django 4.1.7 on 2023-03-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='shop_back.category'),
        ),
    ]
